
version: '3.3'

services:
  web:
    image: juliocarreno/symfony
    restart: always
    volumes:
      - ./code:/var/www/html/
      - ./apache-conf/app.conf:/etc/apache2/sites-enabled/001-app.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db    
    networks: 
      - back

  db:
    image: mysql:5.7
    restart: always
    volumes: 
      - mysql-data:/var/lib/mysql        
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: lugareando
      MYSQL_USER: lugareando
      MYSQL_PASSWORD: toor
    networks:
      - back      

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - back
networks:
  back:
volumes:
  mysql-data: